items:
- uid: System.IO.InvalidDataException
  id: InvalidDataException
  parent: System.IO
  children:
  - System.IO.InvalidDataException.#ctor
  - System.IO.InvalidDataException.#ctor(System.String)
  - System.IO.InvalidDataException.#ctor(System.String,System.Exception)
  name: InvalidDataException
  fullName: System.IO.InvalidDataException
  type: Class
  source:
    remote: &o0
      path: src/System.IO/src/System/IO/InvalidDataException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.IO/src/System/IO/InvalidDataException.cs
    startLine: 6
  assemblies:
  - System.IO
  namespace: System.IO
  summary: The exception that is thrown when a data stream is in an invalid format.
  syntax:
    content: 'public sealed class InvalidDataException : Exception'
    content.vb: Public NotInheritable Class InvalidDataException Inherits Exception
  inheritance:
  - System.Object
- uid: System.IO.InvalidDataException.#ctor
  id: '#ctor'
  parent: System.IO.InvalidDataException
  name: InvalidDataException()
  fullName: System.IO.InvalidDataException.InvalidDataException()
  type: Constructor
  source:
    remote: *o0
    path: src/System.IO/src/System/IO/InvalidDataException.cs
    startLine: 8
  assemblies:
  - System.IO
  namespace: System.IO
  summary: Initializes a new instance of the <xref href="System.IO.InvalidDataException" data-throw-if-not-resolved="false"></xref> class.
  syntax:
    content: public InvalidDataException()
    content.vb: Public Sub New
- uid: System.IO.InvalidDataException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IO.InvalidDataException
  name: InvalidDataException(String)
  fullName: System.IO.InvalidDataException.InvalidDataException(System.String)
  type: Constructor
  source:
    remote: *o0
    path: src/System.IO/src/System/IO/InvalidDataException.cs
    startLine: 13
  assemblies:
  - System.IO
  namespace: System.IO
  summary: Initializes a new instance of the <xref href="System.IO.InvalidDataException" data-throw-if-not-resolved="false"></xref> class with a specified error message.
  syntax:
    content: public InvalidDataException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: The error message that explains the reason for the exception.
- uid: System.IO.InvalidDataException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IO.InvalidDataException
  name: InvalidDataException(String, Exception)
  fullName: System.IO.InvalidDataException.InvalidDataException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.IO/ref/System.IO.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.IO/ref/System.IO.cs
    startLine: 110
  assemblies:
  - System.IO
  namespace: System.IO
  summary: Initializes a new instance of the <xref href="System.IO.InvalidDataException" data-throw-if-not-resolved="false"></xref> class with a reference to the inner exception that is the cause of this exception.
  syntax:
    content: public InvalidDataException(string message, Exception innerException)
    content.vb: Public Sub New(message As String, innerException As Exception)
    parameters:
    - id: message
      type: System.String
      description: The error message that explains the reason for the exception.
    - id: innerException
      type: System.Exception
      description: The exception that is the cause of the current exception. If the *innerException* parameter is not null, the current exception is raised in a catch block that handles the inner exception.
references:
- uid: System.IO
  isExternal: false
  name: System.IO
  fullName: System.IO
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
