items:
- uid: System.Net.Sockets.SocketException
  id: SocketException
  parent: System.Net.Sockets
  children:
  - System.Net.Sockets.SocketException.#ctor
  - System.Net.Sockets.SocketException.#ctor(System.Int32)
  - System.Net.Sockets.SocketException.Message
  - System.Net.Sockets.SocketException.SocketErrorCode
  name: SocketException
  fullName: System.Net.Sockets.SocketException
  type: Class
  source:
    remote:
      path: src/System.Net.Primitives/src/System/Net/SocketException.Windows.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Net.Primitives/src/System/Net/SocketException.Windows.cs
    startLine: 9
  assemblies:
  - System.Net.Primitives
  namespace: System.Net.Sockets
  summary: The exception that is thrown when a socket error occurs.
  syntax:
    content: 'public class SocketException : Exception'
    content.vb: Public Class SocketException Inherits Exception
  inheritance:
  - System.Object
- uid: System.Net.Sockets.SocketException.#ctor
  id: '#ctor'
  parent: System.Net.Sockets.SocketException
  name: SocketException()
  fullName: System.Net.Sockets.SocketException.SocketException()
  type: Constructor
  source:
    remote: &o0
      path: src/System.Net.Primitives/src/System/Net/SocketException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Net.Primitives/src/System/Net/SocketException.cs
    startLine: 24
  assemblies:
  - System.Net.Primitives
  namespace: System.Net.Sockets
  summary: Initializes a new instance of the <xref href="System.Net.Sockets.SocketException" data-throw-if-not-resolved="false"></xref> class with the last operating system error code.
  syntax:
    content: public SocketException()
    content.vb: Public Sub New
- uid: System.Net.Sockets.SocketException.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: System.Net.Sockets.SocketException
  name: SocketException(Int32)
  fullName: System.Net.Sockets.SocketException.SocketException(System.Int32)
  type: Constructor
  source:
    remote: *o0
    path: src/System.Net.Primitives/src/System/Net/SocketException.cs
    startLine: 42
  assemblies:
  - System.Net.Primitives
  namespace: System.Net.Sockets
  summary: Initializes a new instance of the <xref href="System.Net.Sockets.SocketException" data-throw-if-not-resolved="false"></xref> class with the specified error code.
  syntax:
    content: public SocketException(int errorCode)
    content.vb: Public Sub New(errorCode As Integer)
    parameters:
    - id: errorCode
      type: System.Int32
      description: The error code that indicates the error that occurred.
- uid: System.Net.Sockets.SocketException.Message
  id: Message
  parent: System.Net.Sockets.SocketException
  name: Message
  fullName: System.Net.Sockets.SocketException.Message
  type: Property
  source:
    remote: *o0
    path: src/System.Net.Primitives/src/System/Net/SocketException.cs
    startLine: 74
  assemblies:
  - System.Net.Primitives
  namespace: System.Net.Sockets
  summary: Gets the error message that is associated with this exception.
  syntax:
    content: public override string Message { get; }
    content.vb: Public Overrides ReadOnly Property Message As String
    parameters: []
    return:
      type: System.String
      description: A string that contains the error message.
- uid: System.Net.Sockets.SocketException.SocketErrorCode
  id: SocketErrorCode
  parent: System.Net.Sockets.SocketException
  name: SocketErrorCode
  fullName: System.Net.Sockets.SocketException.SocketErrorCode
  type: Property
  source:
    remote: *o0
    path: src/System.Net.Primitives/src/System/Net/SocketException.cs
    startLine: 89
  assemblies:
  - System.Net.Primitives
  namespace: System.Net.Sockets
  summary: Gets the error code that is associated with this exception.
  syntax:
    content: public SocketError SocketErrorCode { get; }
    content.vb: Public ReadOnly Property SocketErrorCode As SocketError
    parameters: []
    return:
      type: System.Net.Sockets.SocketError
      description: An integer error code that is associated with this exception.
references:
- uid: System.Net.Sockets
  isExternal: false
  name: System.Net.Sockets
  fullName: System.Net.Sockets
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  fullName: System.Int32
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Net.Sockets.SocketError
  parent: System.Net.Sockets
  isExternal: false
  name: SocketError
  fullName: System.Net.Sockets.SocketError
